using System;
using System.Collections;
using System.Collections.Generic;
using DG.Tweening;
using EasyUI.Toast;
using JetBrains.Annotations;
using Mkey;
using Newtonsoft;
using Newtonsoft.Json;
//using Profile;
using TMPro;
using UniRx;
using UnityEditor;
using UnityEngine;
using UnityEngine.Networking;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

//using UnityEngine.Windows.Speech;
//using static UnityEngine.Rendering.DebugUI;

namespace AndroApps
{
    public class AuthManager : MonoBehaviour
    {
        public int number;

        [Header("LogIn Fields")]
        public newLogInDetails LogInDetail;

        [Header("SignIn Fields")]
        public newSignUpDetails SignUpDetail;

        [Header("LogInOutput Response")]
        public newLogInOutputs LogInOutput;

        [Header("SignInOutput Response")]
        public newSignUpOutputs SignUpOutput;
        public bool isGuest = false;

        // [Header("Homepageprofile")]
        // public GameObject homepage;
        //  public GameObject loginpanel;

        // [Header("Current player i from playerprefs")]
        // public string id;
        // public UnityEngine.UI.Toggle toggle;
        //  public SetHomePageDetails details;

        // [Header("Profile Details")]
        // public Text username;
        // public Text userID,
        //     usercoins;
        // public Image profilepic,
        //     profilepic2;

        // [Header("ProfileDetiails")]
        // public InputField entername;
        // public InputField bankaccountnumber,
        //     adhaarnumber,
        //     UPInumber,
        //     phonenumber;

        // public RectTransform[] panels; // Assign the panels in the inspector
        // public UnityEngine.UI.Button[] buttons; // Assign the buttons in the inspector

        // [SerializeField]
        // private GameObject Setting;


        //public RectTransform panelToSlide;

        // public Toggle music,
        //     sound;

        private bool isAnimating = false;
        private bool isOpen = false;
        public GameObject forgotpanel;
        private bool isLoginOtpFlow = false;

        [Header("Sing up details")]
        string Mobile,
            Password,
            Name,
            Referral,
            Otp_id;

        public Toggle logintoggle,
            registertoggle;

        public List<TextMeshProUGUI> TMPPlaceholder_Text;
        public List<TextMeshProUGUI> TMPInput_Text;
        public GameBackendData data;
        public int otp_id;
        public TextMeshProUGUI number_otp,
            otp_text;

        // password_text;

        public InputField password_text;
        public GameObject otp_panel,
            password_panel,
            loginpanel;

        void OnEnable()
        {
            foreach (var txt in TMPInput_Text)
            {
                txt.color = data.inputcolor;
            }
            foreach (var txt in TMPPlaceholder_Text)
            {
                txt.color = data.placeholdercolor;
            }
        }

        private void Awake()
        {
            if (Application.platform == RuntimePlatform.Android)
            {
                EnableSystemVolumeControl();
            }
            if (!PlayerPrefs.HasKey("Reffral-ID"))
            {
                string copiedText = GUIUtility.systemCopyBuffer;
                string result = copiedText.Substring(copiedText.IndexOf('-') + 1);
                if (copiedText.Contains("777-"))
                {
                    PlayerPrefs.SetString("Reffral-ID", result);
                    //SignUpDetail.ReferralCodeInputfield.text = result;
                }
            }
        }

        public async void GuestLogin()
        {
            CommonUtil.CheckLog("Login");
            string Url = Configuration.Url + Configuration.guest_register;

            Debug.Log("GuestLogin" + Url);
            string token = GenerateToken();
            var formData = new Dictionary<string, string> { { "unique_token", token } };
            var resp = await APIManager.Instance.Post<Guest>(Url, formData);

            CommonUtil.CheckLog(
                $"RES_Check  + Message: {resp.message}\nRES_Check  + Code: {resp.code}"
            );

            ImageUtil.Instance.isGuest = true;
            PlayerPrefs.SetString("id", resp.user_id);
            PlayerPrefs.SetString("token", resp.token);
            SceneLoader.Instance.LoadDynamicScene("HomePage.unity");
        }

        public async void OpenTermsAndCondition()
        {
            CommonUtil.OpenTandC();
        }

        public async void OpenPrivacyAndPolicy()
        {
            CommonUtil.OpenPrivacyPolicy();
        }

        public static string GenerateToken()
        {
            return System.Guid.NewGuid().ToString();
        }

        private string GenerateAutoName(string mobile)
        {
            if (!string.IsNullOrEmpty(mobile) && mobile.Length >= 4)
                return "User_" + mobile.Substring(mobile.Length - 4);
            return "User_" + UnityEngine.Random.Range(1000, 9999);
        }

        private string GenerateAutoPassword()
        {
            return System.Guid.NewGuid().ToString("N").Substring(0, 8);
        }

        void EnableSystemVolumeControl()
        {
            // Get the current Android Activity
            AndroidJavaClass unityPlayer = new AndroidJavaClass("com.unity3d.player.UnityPlayer");
            AndroidJavaObject currentActivity = unityPlayer.GetStatic<AndroidJavaObject>(
                "currentActivity"
            );

            // Run on UI Thread to set volume control stream to MEDIA
            currentActivity.Call(
                "runOnUiThread",
                new AndroidJavaRunnable(() =>
                {
                    currentActivity.Call("setVolumeControlStream", 3); // STREAM_MUSIC = 3
                })
            );
        }

        #region update data


        string FormatNumber(string number)
        {
            if (float.Parse(number) >= 1000 && float.Parse(number) < 10000)
            {
                return (float.Parse(number) / 1000f).ToString("0.0") + "k";
            }
            else if (float.Parse(number) >= 10000)
            {
                return (float.Parse(number) / 1000).ToString("0.#") + "k";
            }
            else
            {
                return number.ToString();
            }
        }

        public void showtoastmessage(string message)
        {
            Toast.Show(message, 3f);
        }

        public void forgotpassword(TMP_InputField mobilenumber)
        {
            if (mobilenumber.text.Length < 10)
            {
                showtoastmessage("Please Enter Valid Mobile Number");
            }
            else
            {
                UpdatePassword(mobilenumber.text.ToString());
            }
        }

        public async void UpdatePassword(string mobileno)
        {
            number_otp.text = "";
            password_text.text = "";
            CommonUtil.CheckLog("Login");
            if (string.IsNullOrEmpty(mobileno))
            {
                showtoastmessage("Please Enter Valid Mobile Number");
            }
            string Url = Configuration.Url + Configuration.Forgot;

            var formData = new Dictionary<string, string> { { "mobile", mobileno } };
            var resp = await APIManager.Instance.Post<OTP>(Url, formData);

            CommonUtil.CheckLog(
                $"RES_Check  + Message: {resp.message}\nRES_Check  + Code: {resp.code}"
            );

            if (resp.code == 200)
            {
                otp_id = int.Parse(resp.otp_id);
                number_otp.text = mobileno;
                showtoastmessage(resp.message);
                otp_panel.gameObject.SetActive(true);
                password_panel.gameObject.SetActive(false);
            }
            else
            {
                showtoastmessage(resp.message);
            }
        }

        public void clickreset()
        {
            if (otp_text.text.Length > 3)
            {
                ResetPassword();
            }
            else
            {
                showtoastmessage("Please Enter OTP");
            }
        }

        public async void ResetPassword() //string Token)
        {
            string Url = Configuration.Url + Configuration.UpdatePassword;
            CommonUtil.CheckLog("RES_Check + API-Call + UpdatePassword");

            if (password_text.text.Length <= 0)
            {
                showtoastmessage("Enter New Passward");
                return;
            }
            //string passwordnput = password_text.text;
            Debug.Log("PAssword Data " + password_text.text);

            var formData = new Dictionary<string, string>
            {
                { "otp", otp_text.text },
                { "otp_id", otp_id.ToString() },
                { "mobile", number_otp.text },
                { "new_password", password_text.text },
            };
            Debug.Log(JsonUtility.ToJson(formData));

            messageprint resp = new messageprint();
            resp = await APIManager.Instance.Post<messageprint>(Url, formData);

            if (resp.code == 200)
            {
                otp_panel.gameObject.SetActive(false);
                loginpanel.SetActive(true);
            }

            showtoastmessage(resp.message);
        }

        public async void updatedata(string id, string token) //string Token)
        {
            string Url = Configuration.Url + Configuration.profile;
            CommonUtil.CheckLog("RES_Check + API-Call + profile");

            var formData = new Dictionary<string, string>
            {
                { "fcm", Configuration.getFCMToken() },
                { "app_version", "1" },
                { "id", id },
                { "token", token },
            };
            newLogInOutputs LogInOutput = new newLogInOutputs();
            LogInOutput = await APIManager.Instance.Post<newLogInOutputs>(Url, formData);
            if (LogInOutput.code == 411)
            {
                logout();
            }
            if (LogInOutput.code == 200)
            {
                CommonUtil.CheckLog("RES_Check + Login Profile Data : " + LogInOutput.user_data[0]);
                PlayerPrefs.SetString("id", LogInOutput.user_data[0].id);
                PlayerPrefs.SetString("mobile", LogInOutput.user_data[0].mobile);
                PlayerPrefs.SetString("token", LogInOutput.user_data[0].token);
                PlayerPrefs.SetString("wallet", LogInOutput.user_data[0].wallet);
                PlayerPrefs.SetString("profile_pic", LogInOutput.user_data[0].profile_pic);
                PlayerPrefs.SetString("name", LogInOutput.user_data[0].name);

                PlayerPrefs.Save();
            }
            else
            {
                showtoastmessage(LogInOutput.message);
            }
        }
        #endregion

        #region Login
        public void OnClickLogIn()
        {
            if (AudioManager._instance != null)
            {
                AudioManager._instance.ButtonClick();
            }
            number = 0;
            CommonUtil.CheckLog("RES_Check Login Called");
            if (LogInDetail == null)
            {
                showtoastmessage("Login UI not assigned");
                return;
            }
            if (LogInDetail.PasswordInputfield == null || LogInDetail.MobileInputfield == null)
            {
                showtoastmessage("Login fields not assigned");
                return;
            }
            Password = LogInDetail.PasswordInputfield.text;
            Mobile = LogInDetail.MobileInputfield.text;
            if (Mobile == string.Empty)
            {
                showtoastmessage("Please Enter Your Mobile Number");
                return;
            }
            else if (Mobile.Length < 5)
            {
                showtoastmessage("Please Enter Valid Mobile Number");
                return;
            }
            else
            {
                if (!logintoggle.isOn)
                {
                    showtoastmessage("Please agree with our terms & conditions to continue");
                    return;
                }

                if (string.IsNullOrEmpty(Password))
                {
                    // Passwordless login via OTP
                    isLoginOtpFlow = true;
                    PostUserSendOtp(Mobile, "login");
                }
                else
                {
                    // Traditional password login
                    isLoginOtpFlow = false;
                    LogInId(Password, Mobile);
                }
            }
        }

        public void OnClickGuest()
        {
            GuestLogin();
        }

        private bool isprossesing = false;

        public async void LogInId(string Password, string Mobile) //string Token)
        {
            if (isprossesing)
                return;
            isprossesing = true;
            CommonUtil.CheckLog("Login");

            string Url = Configuration.Url + Configuration.LogIn;

            var formData = new Dictionary<string, string>
            {
                { "mobile", Mobile },
                { "password", Password },
            };
            // Ensure APIManager instance exists
            var apiManager = APIManager.Instance ?? UnityEngine.Object.FindObjectOfType<APIManager>();
            if (apiManager == null)
            {
                var go = new GameObject("APIManager");
                apiManager = go.AddComponent<APIManager>();
            }

            newLogInOutputs LogInOutput = new newLogInOutputs();
            LogInOutput = await apiManager.Post<newLogInOutputs>(Url, formData);

            if (LogInOutput.code == 200)
            {
                CommonUtil.CheckLog("RES_Check + Profile Data : " + LogInOutput.user_data[0]);
                PlayerPrefs.SetString("id", LogInOutput.user_data[0].id);
                PlayerPrefs.SetString("token", LogInOutput.user_data[0].token);
                PlayerPrefs.SetString("wallet", LogInOutput.user_data[0].wallet);
                PlayerPrefs.SetString("profile_pic", LogInOutput.user_data[0].profile_pic);
                PlayerPrefs.SetString("name", LogInOutput.user_data[0].name);
                PlayerPrefs.SetString("MyEmail", LogInOutput.user_data[0].email);
                PlayerPrefs.Save();
                if (LogInDetail != null && LogInDetail.LogInPnl != null)
                    LogInDetail.LogInPnl.SetActive(false);
                //CurrentPackage.passbook_img = LogInOutput.user_bank_details[0].passbook_img;

                if (LogInDetail != null)
                {
                    if (LogInDetail.PasswordInputfield != null)
                        LogInDetail.PasswordInputfield.text = string.Empty;
                    if (LogInDetail.MobileInputfield != null)
                        LogInDetail.MobileInputfield.text = string.Empty;
                }
                GetProfileImage(LogInOutput.user_data[0].profile_pic);
                //util.instance.LoadScene("DNT");
            }
            else
            {
                CommonUtil.CheckLog("error" + LogInOutput.message);
                showtoastmessage(LogInOutput.message);
            }
            isprossesing = false;
        }
        #endregion

        public async void GetProfileImage(string profile_pic)
        {
            // string profile_url = Configuration.ProfileImage + profile_pic;
            // SpriteManager.Instance.profile_image = await ImageUtil.Instance.GetSpriteFromURLAsync(
            //     profile_url
            // );
            if (SpriteManager.Instance != null)
            {
                await SpriteManager.Instance.UpdateData(
                    Configuration.GetId(),
                    Configuration.GetToken()
                );
            }

            // After login, show Loading scene then HomePage
            if (!IsSceneInBuildSettings("HomePage"))
            {
                showtoastmessage("HomePage scene not in Build Settings. Add it and retry.");
                return;
            }
            if (!IsSceneInBuildSettings("Loading"))
            {
                UnityEngine.SceneManagement.SceneManager.LoadSceneAsync("HomePage");
                return;
            }
            UnityEngine.Object.DontDestroyOnLoad(this.gameObject);
            StartCoroutine(TransitionViaLoading("HomePage"));
            //SceneManager.LoadSceneAsync("HomePage");
            // StartCoroutine(
            //     ImageUtil.Instance.DownloadImage(
            //         profile_pic,
            //         Configuration.ProfileImage,
            //         sprite =>
            //         {
            //             if (sprite != null)
            //             { //                 // Use the sprite (e.g., assign to an Image component)
            //                 SpriteManager.Instance.welcome_app_banner = sprite;
            //             }
            //             else
            //             {
            //                 LogUtil.CheckLogError("Failed to download or create sprite.");
            //             }
            //         }
            //     )
            // );
        }

        #region Logout

        public void logout()
        {
            PlayerPrefs.DeleteAll();
            LogInDetail.LogInPnl.SetActive(true);
            //homepage.SetActive(false);
        }

        #endregion

        #region HomePage

        public void ShowHomePage()
        {
            //pmanager.setuserdetails();
            SceneManager.LoadSceneAsync("OPTHomePage");
            //StartCoroutine(details.GetProfileDetails());
        }

        #endregion

        #region Signup
        public void OnClickSignUp()
        {
            CommonUtil.CheckLog("signup click");
            number = 1;
            if (SignUpDetail == null || SignUpDetail.MobileInputfield == null)
            {
                showtoastmessage("Signup UI not assigned");
                return;
            }
            Mobile = SignUpDetail.MobileInputfield.text;
            // Auto-generate name and password
            Name = GenerateAutoName(Mobile);
            Password = GenerateAutoPassword();
            Referral = SignUpDetail != null && SignUpDetail.ReferralCodeInputfield != null
                ? SignUpDetail.ReferralCodeInputfield.text
                : string.Empty;

            if (Mobile == string.Empty)
            {
                showtoastmessage("Please Enter Your Mobile Number");
                return;
            }
            else if (Mobile.Length < 10)
            {
                showtoastmessage("Please Enter Valid Mobile Number");
                return;
            }
            else
            {
                if (registertoggle.isOn)
                    PostUserSendOtp(Mobile, "register");
                else
                    showtoastmessage("Please agree with our terms & conditions to continue");
            }
        }

        public async void PostUserSendOtp(string mobile, string type)
        {
            string Url = Configuration.Url + Configuration.Usersendotp;
            var formData = new Dictionary<string, string>
            {
                { "mobile", mobile },
                { "type", type },
                { "referral_code", Referral },
            };
            Debug.Log("Referral" + Referral);
            // Ensure APIManager instance exists
            var apiManager = APIManager.Instance ?? UnityEngine.Object.FindObjectOfType<APIManager>();
            if (apiManager == null)
            {
                var go = new GameObject("APIManager");
                apiManager = go.AddComponent<APIManager>();
            }

            var otpResponse = await apiManager.Post<OtpOutputs>(Url, formData);

            // Update shared state only if OtpManager exists
            if (OtpManager.Instance != null)
            {
                OtpManager.Instance.OtpOutput = otpResponse;
            }

            Otp_id = otpResponse.otp_id.ToString();
            CommonUtil.CheckLog("Response SignUp : " + LogInOutput.message);

            if (otpResponse.code == 200)
            {
                SignUpDetail.OtpPanel.SetActive(true);
                SignUpDetail.SignUpPnl.SetActive(false);
            }
            else if (otpResponse.code == 404)
            {
                showtoastmessage(otpResponse.message);
            }
        }

        public void OnClickOtp()
        {
            number = 2;
            CommonUtil.CheckLog("OTP click");

            //if (OtpManager.Instance.OtpDetail.MobileInputfield.text == )
            if (OtpManager.Instance == null || OtpManager.Instance.OtpDetail == null || OtpManager.Instance.OtpDetail.OTPCodeInputfield == null)
            {
                showtoastmessage("OTP UI not assigned");
                return;
            }
            if (OtpManager.Instance.OtpDetail.OTPCodeInputfield.text.Length <= 0)
            {
                showtoastmessage("Please Enter OTP");
            }
            else if (OtpManager.Instance.OtpDetail.OTPCodeInputfield.text.Length >= 1)
            {
                string otp = OtpManager.Instance.OtpDetail.OTPCodeInputfield.text;
                if (isLoginOtpFlow)
                {
                    // Auto-generate name and password for OTP login flow
                    string autoName = GenerateAutoName(Mobile);
                    string autoPassword = GenerateAutoPassword();
                    PostSignup(
                        autoName,
                        Mobile,
                        autoPassword,
                        Referral,
                        otp,
                        Otp_id,
                        "login",
                        Application.productName
                    );
                }
                else
                {
                    PostSignup(
                        Name,
                        Mobile,
                        Password,
                        Referral,
                        otp,
                        Otp_id,
                        "register",
                        Application.productName
                    );
                }
            }
            // else
            // {
            //     showtoastmessage("Please Enter Minimum 4 Digit");
            // }
        }

        async void PostSignup(
            string Name,
            string mobile,
            string Password,
            string Referrel,
            string otp,
            string otp_id,
            string type,
            string app
        )
        {
            string Url = Configuration.Url + Configuration.Signup;

            var formData = new Dictionary<string, string>
            {
                { "name", Name },
                { "mobile", mobile },
                { "password", Password },
                { "type", type },
                { "otp_id", otp_id },
                { "otp", otp },
                { "gender", "m" },
                { "app", app },
                { "referral_code", Referrel },
            };
            Debug.Log("Name: " + Name);
Debug.Log("mobile: " + mobile);
Debug.Log("Password: " + Password);
Debug.Log("otp: " + otp);
Debug.Log("otp_id: " + otp_id);
Debug.Log("type: " + type);
Debug.Log("app: " + app);
            // Ensure APIManager instance exists
            var apiManager = APIManager.Instance ?? UnityEngine.Object.FindObjectOfType<APIManager>();
            if (apiManager == null)
            {
                var go = new GameObject("APIManager");
                apiManager = go.AddComponent<APIManager>();
            }

            SignUpOutput = new newSignUpOutputs();
            SignUpOutput = await apiManager.Post<newSignUpOutputs>(Url, formData);
            if (SignUpOutput.code == 200)
            {
                // Show Loading scene first, then load HomePage
                if (!IsSceneInBuildSettings("HomePage"))
                {
                    showtoastmessage("HomePage scene not in Build Settings. Add it and retry.");
                }
                else if (!IsSceneInBuildSettings("Loading"))
                {
                    // Fallback: load HomePage directly if Loading scene is missing
                    UnityEngine.SceneManagement.SceneManager.LoadSceneAsync("HomePage");
                }
                else
                {
                    // Persist while we transition via Loading scene
                    UnityEngine.Object.DontDestroyOnLoad(this.gameObject);
                    StartCoroutine(TransitionViaLoading("HomePage"));
                }

                if (SignUpDetail != null)
                {
                    if (SignUpDetail.MobileInputfield != null)
                        SignUpDetail.MobileInputfield.text = "";
                    if (SignUpDetail.PasswordInputfield != null)
                        SignUpDetail.PasswordInputfield.text = "";
                    if (SignUpDetail.NameInputfield != null)
                        SignUpDetail.NameInputfield.text = "";
                }
                PlayerPrefs.SetString("id", SignUpOutput.user_id);
                PlayerPrefs.SetString("token", SignUpOutput.token);
                PlayerPrefs.Save();
                if (LogInDetail != null && LogInDetail.LogInPnl != null)
                    LogInDetail.LogInPnl.SetActive(false);
                if (SignUpDetail != null)
                {
                    if (SignUpDetail.SignUpPnl != null)
                        SignUpDetail.SignUpPnl.SetActive(false);
                    if (SignUpDetail.OtpPanel != null)
                        SignUpDetail.OtpPanel.SetActive(false);
                }
                CommonUtil.CheckLog("RES_Check + Register");
                if (SignUpOutput.message == "Login")
                {
                    showtoastmessage("Login Successfully");
                    SceneLoader.Instance.LoadDynamicScene("HomePage.unity");

                }
                else
                {
                    showtoastmessage("Registered Successfully");
                    SceneLoader.Instance.LoadDynamicScene("HomePage.unity");
                    
                }

                
            }
            else
            {
                showtoastmessage(SignUpOutput.message);
            }
        }

        private bool IsSceneInBuildSettings(string sceneName)
        {
            for (int i = 0; i < UnityEngine.SceneManagement.SceneManager.sceneCountInBuildSettings; i++)
            {
                string path = UnityEngine.SceneManagement.SceneUtility.GetScenePathByBuildIndex(i);
                if (path.EndsWith("/" + sceneName + ".unity"))
                    return true;
            }
            return false;
        }

        private System.Collections.IEnumerator LoadSceneAsyncByName(string sceneName)
        {
            var async = UnityEngine.SceneManagement.SceneManager.LoadSceneAsync(sceneName);
            while (!async.isDone)
            {
                yield return null;
            }
        }

        private System.Collections.IEnumerator TransitionViaLoading(string targetSceneName)
        {
            var loadLoading = UnityEngine.SceneManagement.SceneManager.LoadSceneAsync("Loading");
            while (!loadLoading.isDone)
            {
                yield return null;
            }
            // Ensure the Loading scene is visible for at least one frame
            yield return null;
            var loadTarget = UnityEngine.SceneManagement.SceneManager.LoadSceneAsync(targetSceneName);
            while (!loadTarget.isDone)
            {
                yield return null;
            }
        }

        #endregion

        #region comming soon

        public void CommingSoon()
        {
            showtoastmessage("Comming Soon");
        }

        #endregion

        #region DoTween panel animation

        private void Start()
        {
            Screen.sleepTimeout = SleepTimeout.NeverSleep;
            ClosePanel();
            SignUpDetail.ReferralCodeInputfield.text = PlayerPrefs.GetString("Reffral-ID");

            // Add listeners to each button
            // for (int i = 0; i < buttons.Length; i++)
            // {
            //     int index = i; // Required to capture the correct value of i in lambda expression
            //     buttons[i].onClick.AddListener(() => AnimatePanel(panels[index]));
            // }
        }

        private void AnimatePanel(RectTransform panel)
        {
            if (isAnimating)
                return; // Prevent multiple clicks while animating

            isAnimating = true;
            // Ensure the panel is initially scaled down
            panel.localScale = Vector3.zero;

            // Animate the panel to scale up to its full size
            panel
                .DOScale(Vector3.one, 0.5f)
                .SetEase(Ease.OutBack)
                .OnComplete(() =>
                {
                    isAnimating = false; // Allow animation again after completion
                });
        }

        public void TogglePanel()
        {
            if (isOpen)
            {
                ClosePanel();
            }
            else
            {
                OpenPanel();
            }
        }

        public void OpenPanel()
        {
            isOpen = true;
            //   panelToSlide.DOAnchorPosX(0, 0.5f).SetEase(Ease.OutQuint);
        }

        public void ClosePanel()
        {
            isOpen = false;
            //panelToSlide.DOAnchorPosX(panelToSlide.rect.width, 1f).SetEase(Ease.OutQuint);
        }
        #endregion

        #region Clear text on click when going to new panel

        public void OnClickClearDatainLogin()
        {
            LogInDetail.MobileInputfield.text = "";
            LogInDetail.PasswordInputfield.text = "";
        }

        public void OnClearSignUpDetails()
        {
            SignUpDetail.Clear();
        }

        #endregion

        #region Go to url

        public void OnClickTandC()
        {
            //Application.OpenURL(Configuration.TermsAndCondititon);
            showtoastmessage("Cannot open this link in Demo Version");
        }

        public void OnClickPrivacyAndPolicy()
        {
            openwebview(Configuration.Website + "privacy-policy.php");
            //Application.OpenURL(Configuration.PrivacyAndpolicy);
            //   showtoastmessage("Cannot open this link in Demo Version");
        }

        public void OnClickContactUs()
        {
            //Application.OpenURL(Configuration.ContactUs);
            showtoastmessage("Cannot open this link in Demo Version");
        }

        public void OnClickDeleteAcc()
        {
            //Application.OpenURL(Configuration.DeleteAccount);
            showtoastmessage("Cannot open this link in Demo Version");
        }

        #endregion
        public void OpenTurmCondition()
        {
            openwebview(Configuration.Website + "terms-conditions.php");
        }

        public void openwebview(string url)
        {
            // LogUtil.CheckLog("RES_check + open" + url);
            // NewAudioManager.instance?.PlayButtonSound();
            // util.instance.ShowUrlPopupPositionSize(url);
            Application.OpenURL(url);
        }

        public void ShowPassward(bool m_on)
        {
            if (m_on)
            {
                LogInDetail.PasswordInputfield.contentType = TMP_InputField.ContentType.Standard;
                SignUpDetail.PasswordInputfield.contentType = TMP_InputField.ContentType.Standard;
            }
            else
            {
                LogInDetail.PasswordInputfield.contentType = TMP_InputField.ContentType.Password;
                SignUpDetail.PasswordInputfield.contentType = TMP_InputField.ContentType.Password;
            }
            LogInDetail.PasswordInputfield.ForceLabelUpdate();
            SignUpDetail.PasswordInputfield.ForceLabelUpdate();
        }
    }
}